const assets = {
  "home/imgHeroAmbientGlow": "/design/home-imgHeroAmbientGlow.svg",
  "home/imgVisualGlow": "/design/home-imgVisualGlow.svg",
  "home/imgStatusDot": "/design/home-imgStatusDot.svg",
  "home/imgTeamAvatars": "/design/home-imgTeamAvatars.svg",
  "home/imgProofIcon": "/design/home-imgProofIcon.svg",
  "home/imgSearchIcon": "/design/home-imgSearchIcon.svg",
  "home/imgThumbnailDecoration": "/design/home-imgThumbnailDecoration.svg",
  "home/imgProjectIconVector": "/design/home-imgProjectIconVector.svg",
  "home/imgProjectIconVector1": "/design/home-imgProjectIconVector1.svg",
  "home/imgProjectIconVector2": "/design/home-imgProjectIconVector2.svg",
  "home/imgProjectIconVector3": "/design/home-imgProjectIconVector3.svg",
  "home/imgProjectIconVector4": "/design/home-imgProjectIconVector4.svg",
  "home/imgProjectIconVector5": "/design/home-imgProjectIconVector5.svg",
  "home/imgProjectIconVector6": "/design/home-imgProjectIconVector6.svg",
  "home/imgProjectIconVector7": "/design/home-imgProjectIconVector7.svg",
  "home/imgBenefitIconVector": "/design/home-imgBenefitIconVector.svg",
  "home/imgBenefitIconVector1": "/design/home-imgBenefitIconVector1.svg",
  "home/imgBenefitIconVector2": "/design/home-imgBenefitIconVector2.svg",
  "home/imgCoverDecoration": "/design/home-imgCoverDecoration.svg",
  "home/imgCoverIconVector": "/design/home-imgCoverIconVector.svg",
  "home/imgMetricIcon": "/design/home-imgMetricIcon.svg",
  "home/imgMetricIcon1": "/design/home-imgMetricIcon1.svg",
  "home/imgMetricIcon2": "/design/home-imgMetricIcon2.svg",
  "home/imgCoverIconVector1": "/design/home-imgCoverIconVector1.svg",
  "home/imgCoverIconVector2": "/design/home-imgCoverIconVector2.svg",
  "dashboard/imgIconProjects": "/design/dashboard-imgIconProjects.svg",
  "dashboard/imgIconFeedback": "/design/dashboard-imgIconFeedback.svg",
  "dashboard/imgIconJoinRequests": "/design/dashboard-imgIconJoinRequests.svg",
  "dashboard/imgIconDeadlines": "/design/dashboard-imgIconDeadlines.svg",
  "dashboard/imgIcon": "/design/dashboard-imgIcon.svg",
  "dashboard/imgIcon1": "/design/dashboard-imgIcon1.svg",
  "dashboard/imgIcon2": "/design/dashboard-imgIcon2.svg",
  "dashboard/imgUnread": "/design/dashboard-imgUnread.svg",
  "dashboard/imgCalendar": "/design/dashboard-imgCalendar.svg",
  "dashboard/imgCalendar1": "/design/dashboard-imgCalendar1.svg",
  "dashboard/imgEllipse": "/design/dashboard-imgEllipse.svg",
  "dashboard/imgEllipse1": "/design/dashboard-imgEllipse1.svg",
  "challenge/imgDecorationGlow": "/design/challenge-imgDecorationGlow.svg",
  "challenge/imgIllustrationTrophy": "/design/challenge-imgIllustrationTrophy.svg",
  "challenge/imgIconSearch": "/design/challenge-imgIconSearch.svg",
  "composer/imgIconAddImage": "/design/composer-imgIconAddImage.svg"
}
export function designIcon(key, className = 'design-icon') {
  return `<img src="${assets[key]}" class="${className}" alt="" aria-hidden="true" width="24" height="24">`
}
export { assets }
